--10)O nome do Deputado Federal mais votado no ano de 2006. (0,9)

SELECT DISTINCT(C.NOME)
FROM CANDIDATO C, VOTACAO V
WHERE C.NUMERO = V.CANDIDATO
AND C.CARGO = 'Deputado Federal'
AND C.NUMERO = 
(
  SELECT CANDIDATO
  FROM
  (
    SELECT CANDIDATO, COUNT(CANDIDATO) AS VOTOS
    FROM VOTACAO
    WHERE ANO = 2006
    GROUP BY CANDIDATO
  )
  WHERE VOTOS = 
  (
    SELECT MAX(COUNT(CANDIDATO)) AS VOTOS
    FROM VOTACAO
    WHERE ANO = 2006
    GROUP BY CANDIDATO
  )
)