--11)O nome do partido do vereador mais votado de 1998. (0,9)

SELECT DISTINCT(NOMEP)
FROM
(
    SELECT C.NOME, COUNT(C.NOME) VOTOS, C.NUMERO AS NUMERO, P.NOME AS NOMEP
    FROM VOTACAO V, CANDIDATO C, PARTIDO P
    WHERE C.NUMERO = V.CANDIDATO
    AND V.ANO = 1998
    AND C.CARGO = 'Vereador'
    AND P.SIGLA = C.PARTIDO
    GROUP BY C.NOME, C.NUMERO, P.NOME
    --ORDER BY VOTOS DESC
), PARTIDO P
WHERE VOTOS = 
(
    SELECT MAX(VOTOS)
    FROM
    (
        SELECT C.NOME, COUNT(C.NOME) VOTOS, C.NUMERO AS NUMERO
        FROM VOTACAO V, CANDIDATO C
        WHERE C.NUMERO = V.CANDIDATO
        AND V.ANO = 1998
        AND C.CARGO = 'Vereador'
        GROUP BY C.NOME, C.NUMERO
        ORDER BY VOTOS DESC
    )
)
