--11)O nome do partido do vereador mais votado de 1998. (0,9)

SELECT DISTINCT(P.NOME)
FROM CANDIDATO C, VOTACAO V, PARTIDO P
WHERE C.NUMERO = V.CANDIDATO
AND P.SIGLA = C.PARTIDO
AND C.CARGO = 'Vereador'
AND C.NUMERO = 
(
  SELECT CANDIDATO
  FROM
  (
    SELECT CANDIDATO, COUNT(CANDIDATO) AS VOTOS
    FROM VOTACAO
    WHERE ANO = 1998
    GROUP BY CANDIDATO
  )
  WHERE VOTOS = 
  (
    SELECT MAX(COUNT(CANDIDATO)) AS VOTOS
    FROM VOTACAO
    WHERE ANO = 2006
    GROUP BY CANDIDATO
  )
)