--12)A sigla do partido que elegeu o Prefeito de 1998. (0,9)

SELECT DISTINCT(SIGLAP)
FROM
(
    SELECT C.NOME, COUNT(C.NOME) VOTOS, C.NUMERO AS NUMERO, P.SIGLA AS SIGLAP
    FROM VOTACAO V, CANDIDATO C, PARTIDO P
    WHERE C.NUMERO = V.CANDIDATO
    AND V.ANO = 1998
    AND C.CARGO = 'Prefeito'
    AND P.SIGLA = C.PARTIDO
    GROUP BY C.NOME, C.NUMERO, P.SIGLA
    ORDER BY VOTOS DESC
), PARTIDO P
WHERE VOTOS = 
(
    SELECT MAX(VOTOS)
    FROM
    (
        SELECT C.NOME, COUNT(C.NOME) VOTOS, C.NUMERO AS NUMERO
        FROM VOTACAO V, CANDIDATO C
        WHERE C.NUMERO = V.CANDIDATO
        AND V.ANO = 1998
        AND C.CARGO = 'Prefeito'
        GROUP BY C.NOME, C.NUMERO
        ORDER BY VOTOS DESC
    )
)














