--12)A sigla do partido que elegeu o Prefeito de 1998. (0,9)

SELECT P.SIGLA
FROM PARTIDO P, CANDIDATO C, VOTACAO V
WHERE P.SIGLA = C.PARTIDO
AND C.NUMERO = V.CANDIDATO
AND C.CARGO = 'Prefeito'
AND V.ANO = 1998
GROUP BY P.SIGLA
HAVING COUNT(C.NOME) = 
(
    SELECT MAX(VOTOS)
    FROM
    (
        SELECT COUNT(C.NOME) AS VOTOS
        FROM PARTIDO P, CANDIDATO C, VOTACAO V
        WHERE P.SIGLA = C.PARTIDO
        AND C.NUMERO = V.CANDIDATO
        AND C.CARGO = 'Prefeito'
        AND V.ANO = 1998
        GROUP BY C.NOME
    )
)