--12)A sigla do partido que elegeu o Prefeito de 1998. (0,9)


SELECT DISTINCT(P.SIGLA)
FROM CANDIDATO C, VOTACAO V, PARTIDO P
WHERE C.NUMERO = V.CANDIDATO
AND P.SIGLA = C.PARTIDO
AND C.CARGO = 'Prefeito'
AND C.NUMERO = 
(
  SELECT CANDIDATO
  FROM
  (
    SELECT CANDIDATO, COUNT(CANDIDATO) AS VOTOS
    FROM VOTACAO
    WHERE ANO = 1998
    GROUP BY CANDIDATO
  )
  WHERE VOTOS = 
  (
    SELECT MAX(COUNT(CANDIDATO)) AS VOTOS
    FROM VOTACAO
    WHERE ANO = 1998
    GROUP BY CANDIDATO
  )
)

SELECT *
FROM VOTACAO V
WHERE V.ANO = 1998

