--8) O número de votos recebidos em 1998 para o cargo de “Vereador”, por partido.


SELECT COUNT(*) AS NUMERO_VOTOS, P.SIGLA
FROM CANDIDATO C, VOTACAO V, ELEITOR E, PARTIDO P
WHERE C.CARGO = 'Vereador'
AND C.NUMERO = V.CANDIDATO
AND V.ANO = 1998
AND E.TITULO = V.ELEITOR
AND P.SIGLA = C.PARTIDO
GROUP BY P.SIGLA
